### ISSUE TITLE
What can be the reasons for traces not showing up

### ISSUE THREAD

**Issue by Ge7alt** [Arize-ai/phoenix#2165]
I was trying the tutorial tracing with langchain. While i ran the on a colab, the traces are showing up properly. but when i downloaded the  tutorial notebook, the traces are not showing up at all when running the chain.

the queries_df and retrieved_documents_df is also empty
![image](https://github.com/Arize-ai/phoenix/assets/59174623/995dda41-e895-4cb6-b558-e9a185a73528)

**Comment by RogerHYang** [comment]
Hi @Ge7alt. Are you running this [notebook](https://github.com/Arize-ai/phoenix/blob/main/tutorials/tracing/langchain_tracing_tutorial.ipynb)? I tried it locally on Jupyter and vscode and was not able to reproduce. See my screenshot below. 

Just to confirm, are you launching your app like the following
```python
session = px.launch_app()
```

### jupyter
<img width="500" alt="Screenshot 2024-02-02 at 9 55 43 AM" src="https://github.com/Arize-ai/phoenix/assets/80478925/1b312d43-e8fe-4b83-a4a8-62df7afb13bf">

### vscode
<img width="500" alt="Screenshot 2024-02-02 at 10 02 39 AM" src="https://github.com/Arize-ai/phoenix/assets/80478925/270b42a4-0bf7-43ab-87f6-262187f6fd50">

**Comment by RogerHYang** [comment]
Hi @Ge7alt. Are you running Windows by any chance? If so, we're releasing a in the next release.

In the meantime you can use this workaround as follows, by declaring the address before initializing the instrumentor.

```python
import os 

os.environ["PHOENIX_COLLECTOR_ENDPOINT"] = "http://127.0.0.1:6006/"

tracer = OpenInferenceTracer()
LangChainInstrumentor(tracer=tracer).instrument()
```

**Comment by RogerHYang** [comment]
We have published a new version 2.8.0. Hopefully that fixes this.

**Comment by mikeldking** [comment]
We hope it's resolved @Ge7alt ! please re-open if still facing!
